### PR TITLE
update readme wording

### PR DESCRIPTION
**Pull request by kylehoehns**

### CODE REVIEW

**Comment by AndreasChristianson** [comment]
related to https://github.com/sourceallies/.github/pull/2#discussion_r859942244

**Comment by AndreasChristianson** [comment]
I took a swing at further wordsmithing

**Review by kylehoehns — COMMENTED** [review]
Changes look good to me. Lets :shipit:

**Comment by AndreasChristianson** [comment]
Adding @nkringle

**Review by AndreasChristianson — APPROVED** [review]

**Comment by AndreasChristianson** [comment]
I wrote some of this, self-approving since it is just a readme change

**Comment by nkringle** [comment]
Thanks for adding me, I think what is there is great but I would also probably including some of the additional details (or at least direct links) that are on the [careers page](https://www.sourceallies.com/careers/). I'm thinking benefits (probably near the bottom), flat organization (and why that's awesome), and a desire to pursue mastery (probably what I would highlight).

**Pull request merged**
